/**
 * The lightweight course outline: every unit and lesson *title* in every
 * course, with no phrases, exercises or audio.
 *
 * Navigation, progress maths and course browsing all read this instead of
 * `@/lib/content`, which carries the full 1.7MB of curriculum data. The file is
 * generated by `npm run build:course-index` and kept honest by
 * `npm run test:course-index`.
 */

import rawIndex from "../../content/course-index.json";
import {
  COURSE_IDS,
  LARGE_COURSE_UNIT_COUNT,
  type CourseId,
} from "@/lib/courses";
import type { UnitSection } from "@/types/learning";

export type LessonOutline = {
  id: string;
  title: string;
  summary: string;
  difficulty: string;
  phraseCount: number;
  /** History chapters only: the icon shown on the path. */
  icon?: string;
};

export type UnitOutline = {
  id: string;
  number: number;
  title: string;
  description: string;
  section?: UnitSection;
  lessons: LessonOutline[];
};

export type CourseOutline = {
  id: CourseId;
  unitCount: number;
  lessonCount: number;
  units: UnitOutline[];
};

export type CourseIndex = {
  version: number;
  courses: Record<CourseId, CourseOutline>;
};

const index = rawIndex as CourseIndex;

const EMPTY_OUTLINE: CourseOutline = {
  id: COURSE_IDS[0],
  unitCount: 0,
  lessonCount: 0,
  units: [],
};

export function getCourseOutline(courseId: CourseId): CourseOutline {
  return index.courses[courseId] ?? EMPTY_OUTLINE;
}

export function getAllCourseOutlines(): CourseOutline[] {
  return COURSE_IDS.map(getCourseOutline);
}

/** Flat lesson list for a course, in path order. */
const flatLessonCache = new Map<CourseId, LessonOutline[]>();

export function getCourseLessons(courseId: CourseId): LessonOutline[] {
  const cached = flatLessonCache.get(courseId);

  if (cached) {
    return cached;
  }

  const flat = getCourseOutline(courseId).units.flatMap((unit) => unit.lessons);
  flatLessonCache.set(courseId, flat);
  return flat;
}

const lessonIdCache = new Map<CourseId, Set<string>>();

/** Lesson ids belonging to a course — used to scope mistakes and completions. */
export function getCourseLessonIds(courseId: CourseId): Set<string> {
  const cached = lessonIdCache.get(courseId);

  if (cached) {
    return cached;
  }

  const ids = new Set(getCourseLessons(courseId).map((lesson) => lesson.id));
  lessonIdCache.set(courseId, ids);
  return ids;
}

export type LessonLocation = {
  courseId: CourseId;
  unit: UnitOutline;
  lesson: LessonOutline;
  /** 0-based index within the whole course. */
  lessonIndex: number;
  /** 0-based index of the unit within the course. */
  unitIndex: number;
};

const locationCache = new Map<string, LessonLocation>();
let locationsBuilt = false;

function buildLocations() {
  if (locationsBuilt) {
    return;
  }

  locationsBuilt = true;

  for (const courseId of COURSE_IDS) {
    let lessonIndex = 0;

    getCourseOutline(courseId).units.forEach((unit, unitIndex) => {
      unit.lessons.forEach((lesson) => {
        locationCache.set(lesson.id, {
          courseId,
          unit,
          lesson,
          lessonIndex,
          unitIndex,
        });
        lessonIndex += 1;
      });
    });
  }
}

/** Where a lesson sits, across all courses. */
export function locateLesson(lessonId: string): LessonLocation | undefined {
  buildLocations();
  return locationCache.get(lessonId);
}

export function getUnitOutline(
  courseId: CourseId,
  unitId: string,
): UnitOutline | undefined {
  return getCourseOutline(courseId).units.find((unit) => unit.id === unitId);
}

export type SectionGroup = {
  /** Section number, or 0 for courses with no sections. */
  number: number;
  title: string;
  description?: string;
  units: UnitOutline[];
};

const sectionCache = new Map<CourseId, SectionGroup[]>();

/**
 * Units grouped into sections. Courses without section metadata come back as a
 * single implicit group so callers can treat every course the same way.
 */
export function getCourseSections(courseId: CourseId): SectionGroup[] {
  const cached = sectionCache.get(courseId);

  if (cached) {
    return cached;
  }

  const outline = getCourseOutline(courseId);
  const groups: SectionGroup[] = [];
  const byNumber = new Map<number, SectionGroup>();

  for (const unit of outline.units) {
    const number = unit.section?.number ?? 0;
    let group = byNumber.get(number);

    if (!group) {
      group = {
        number,
        title: unit.section?.title ?? "All units",
        description: unit.section?.description,
        units: [],
      };
      byNumber.set(number, group);
      groups.push(group);
    }

    group.units.push(unit);
  }

  sectionCache.set(courseId, groups);
  return groups;
}

/** True when a course is big enough to need windowed browsing. */
export function isLargeCourse(courseId: CourseId): boolean {
  return getCourseOutline(courseId).unitCount > LARGE_COURSE_UNIT_COUNT;
}

/**
 * The lesson the learner should do next: the first one they haven't completed,
 * falling back to the first lesson in the course.
 */
export function findNextLesson(
  courseId: CourseId,
  completedLessonIds: Set<string>,
): LessonOutline | undefined {
  const lessons = getCourseLessons(courseId);
  return (
    lessons.find((lesson) => !completedLessonIds.has(lesson.id)) ?? lessons[0]
  );
}

/** The lesson right after this one in path order. */
export function findFollowingLesson(
  lessonId: string,
): LessonOutline | undefined {
  const location = locateLesson(lessonId);

  if (!location) {
    return undefined;
  }

  return getCourseLessons(location.courseId)[location.lessonIndex + 1];
}
