-- Spanish curriculum catalog (seeded from content/spanish-curriculum.json).
--
-- Every table keeps two ids: `external_id` is the stable id from the curriculum
-- pack (used for lookups and re-seeding), and `id` is a separate internal uuid
-- generated by the seed process. Provenance is preserved verbatim per unit.
--
-- This catalog is read-only reference data: public SELECT, no user writes.

create table public.curriculum_courses (
  id uuid primary key,
  external_id text not null unique,
  course_id text not null,
  title text not null,
  version text not null,
  target text not null
);

create table public.curriculum_sections (
  id uuid primary key,
  external_id text not null unique,
  course_id text not null,
  section integer not null,
  cefr text not null
);

create table public.curriculum_units (
  id uuid primary key,
  external_id text not null unique,
  course_id text not null,
  section integer not null,
  unit integer not null,
  title text not null,
  cefr text not null,
  review_schedule_days jsonb not null,
  -- Preserved verbatim from the pack; do not strip (see CLAUDE.md).
  provenance jsonb not null
);

create table public.curriculum_vocabulary_items (
  id uuid primary key,
  external_id text not null unique,
  unit_external_id text not null references public.curriculum_units(external_id) on delete cascade,
  spanish text not null,
  english text not null,
  part_of_speech text not null
);

create table public.curriculum_phrase_patterns (
  id uuid primary key,
  external_id text not null unique,
  unit_external_id text not null references public.curriculum_units(external_id) on delete cascade,
  spanish text not null,
  english text not null
);

create table public.curriculum_lessons (
  id uuid primary key,
  external_id text not null unique,
  unit_external_id text not null references public.curriculum_units(external_id) on delete cascade,
  lesson_index integer not null,
  name text not null,
  goal text not null
);

create table public.curriculum_generated_exercises (
  id uuid primary key,
  external_id text not null unique,
  lesson_external_id text not null references public.curriculum_lessons(external_id) on delete cascade,
  type text not null,
  -- Full generated exercise, including acceptable_answers stored as an array
  -- (multiple valid translations are allowed — see CLAUDE.md).
  payload jsonb not null
);

create index curriculum_units_course_idx on public.curriculum_units (course_id);
create index curriculum_vocab_unit_idx on public.curriculum_vocabulary_items (unit_external_id);
create index curriculum_phrase_unit_idx on public.curriculum_phrase_patterns (unit_external_id);
create index curriculum_lessons_unit_idx on public.curriculum_lessons (unit_external_id);
create index curriculum_exercises_lesson_idx on public.curriculum_generated_exercises (lesson_external_id);
